export const companyName ="SeedLink"
export const tagline1 ="Where Nature finds Home  "
export const tagline2 ="Growing Passion, One Seed at a Time "
export const tagline3 ="From Seed to Satisfaction: Cultivating Your Passion for Growth! "
export const tagline4 ="Planting Pleasure, Cultivating Desire "
